@startuml
title SmartHouse Devices Management Code Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

class User {
  +String id
  +String name
  +String email
  +List<Devices> devices
  +void register()
  +void login()

  +void addDevice()
  +void removeDevice()
}

class Device {
  +String id
  +String manufacturer
  +String type
  +String model
  +String number
  +String name
  +String zone_id
  +Date startDate
  +Date endDate

  +void setZone()
  +void resetZone()
}

class Zone {
  +String id
  +String parent_zone_id
  +String name

  +void addZone()
  +void removeZone()
}

User "1" -- "0..*" Device : has
Zone "1" -- "0..*" Device : has

@enduml